config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'
  resources :exhibitions
  resources :venues
  resources :artworks

  get 'sessions/new' => 'sessions#new'
  
  post 'sessions' => 'sessions#create'
  
  delete 'sessions' => 'sessions#destroy'

  namespace :admin, defaults: {format: :html} do
    root to: '/sessions#new'
    resources :exhibitions
    resources :venues
    resources :artworks
    resources :artwork_images
  end

end

app/models/exhibition.rb
class Exhibition < ActiveRecord::Base
  has_many :artworks
  has_many :artwork_images, through: :artworks
  belongs_to :venue
end

app/controllers/admin/exhibitions_controller.rb
module Admin
  class ExhibitionsController < ApplicationController
  before_action :set_exhibition, only: [:show, :edit, :update, :destroy]

  # GET /exhibitions
  # GET /exhibitions.json
  def index
    @exhibitions = Exhibition.all
  end

  # GET /exhibitions/1
  # GET /exhibitions/1.json
  def show
  end

  # GET /exhibitions/new
  def new
    @exhibition = Exhibition.new
  end

  # GET /exhibitions/1/edit
  def edit
  end

  # POST /exhibitions
  # POST /exhibitions.json
  def create
    @exhibition = Exhibition.new(exhibition_params)

    respond_to do |format|
      if @exhibition.save
        format.html { redirect_to admin_exhibitions_path, notice: 'Exhibition was successfully created.' }
        format.json { render :show, status: :created, location: @exhibition }
      else
        format.html { render :new }
        format.json { render json: @exhibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exhibitions/1
  # PATCH/PUT /exhibitions/1.json
  def update
    respond_to do |format|
      if @exhibition.update(exhibition_params)
        format.html { redirect_to @exhibition, notice: 'Exhibition was successfully updated.' }
        format.json { render :show, status: :ok, location: @exhibition }
      else
        format.html { render :edit }
        format.json { render json: @exhibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exhibitions/1
  # DELETE /exhibitions/1.json
  def destroy
    @exhibition.destroy
    respond_to do |format|
      format.html { redirect_to exhibitions_url, notice: 'Exhibition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exhibition
      @exhibition = Exhibition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exhibition_params
      params.require(:exhibition).permit(:venue_id, :title, :subtitle, :exhibition_type, :press_url, :curator, :start_month, :finish_month, :year, :exhibition_image_url, :exhibition_image_url2)
    end
end

end

app/controllers/exhibitions_controller.rb
class ExhibitionsController < ApplicationController
  before_action :set_exhibition, only: [:show, :edit, :update, :destroy]

  # GET /exhibitions
  # GET /exhibitions.json
  def index
    @exhibitions = Exhibition.all
  end

  # GET /exhibitions/1
  # GET /exhibitions/1.json
  def show
  end

  # GET /exhibitions/new
  def new
    @exhibition = Exhibition.new
  end

  # GET /exhibitions/1/edit
  def edit
  end

  # POST /exhibitions
  # POST /exhibitions.json
  def create
    @exhibition = Exhibition.new(exhibition_params)

    respond_to do |format|
      if @exhibition.save
        format.html { redirect_to @exhibition, notice: 'Exhibition was successfully created.' }
        format.json { render :show, status: :created, location: @exhibition }
      else
        format.html { render :new }
        format.json { render json: @exhibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exhibitions/1
  # PATCH/PUT /exhibitions/1.json
  def update
    respond_to do |format|
      if @exhibition.update(exhibition_params)
        format.html { redirect_to @exhibition, notice: 'Exhibition was successfully updated.' }
        format.json { render :show, status: :ok, location: @exhibition }
      else
        format.html { render :edit }
        format.json { render json: @exhibition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exhibitions/1
  # DELETE /exhibitions/1.json
  def destroy
    @exhibition.destroy
    respond_to do |format|
      format.html { redirect_to exhibitions_url, notice: 'Exhibition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exhibition
      @exhibition = Exhibition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exhibition_params
      params.require(:exhibition).permit(:venue_id, :title, :subtitle, :exhibition_type, :press_url, :curator, :start_month, :finish_month, :year, :exhibition_image_url, :exhibition_image_url2)
    end
end

app/helpers/exhibitions_helper.rb
module ExhibitionsHelper
end

app/views/admin/exhibitions/_form.html.erb
<%= form_for(@exhibition, url: admin_exhibitions_path) do |f| %>
  <% if @exhibition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exhibition.errors.count, "error") %> prohibited this exhibition from being saved:</h2>

      <ul>
      <% @exhibition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :venue_id %><br>
    <%= f.number_field :venue_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :exhibition_type %><br>
    <%= f.text_field :exhibition_type %>
  </div>
  <div class="field">
    <%= f.label :press_url %><br>
    <%= f.text_field :press_url %>
  </div>
  <div class="field">
    <%= f.label :curator %><br>
    <%= f.text_field :curator %>
  </div>
  <div class="field">
    <%= f.label :start_month %><br>
    <%= f.text_field :start_month %>
  </div>
  <div class="field">
    <%= f.label :finish_month %><br>
    <%= f.text_field :finish_month %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :exhibition_image_url %><br>
    <%= f.text_field :exhibition_image_url %>
  </div>
  <div class="field">
    <%= f.label :exhibition_image_url2 %><br>
    <%= f.text_field :exhibition_image_url2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/exhibitions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exhibitions</h1>

<table>
  <thead>
    <tr>
      <th>Venue</th>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Exhibition type</th>
      <th>Press url</th>
      <th>Curator</th>
      <th>Start month</th>
      <th>Finish month</th>
      <th>Year</th>
      <th>Exhibition image url</th>
      <th>Exhibition image url2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exhibitions.each do |exhibition| %>
      <tr>
        <td><%= exhibition.venue_id %></td>
        <td><%= exhibition.title %></td>
        <td><%= exhibition.subtitle %></td>
        <td><%= exhibition.exhibition_type %></td>
        <td><%= exhibition.press_url %></td>
        <td><%= exhibition.curator %></td>
        <td><%= exhibition.start_month %></td>
        <td><%= exhibition.finish_month %></td>
        <td><%= exhibition.year %></td>
        <td><%= exhibition.exhibition_image_url %></td>
        <td><%= exhibition.exhibition_image_url2 %></td>
        <td><%= link_to 'Show', exhibition %></td>
        <td><%= link_to 'Edit', edit_exhibition_path(exhibition) %></td>
        <td><%= link_to 'Destroy', exhibition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exhibition', new_admin_exhibition_path %>

app/views/admin/exhibitions/new.html.erb
<h1>New Exhibition</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_exhibitions_path %>

app/views/admin/exhibitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Venue:</strong>
  <%= @exhibition.venue_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @exhibition.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @exhibition.subtitle %>
</p>

<p>
  <strong>Exhibition type:</strong>
  <%= @exhibition.exhibition_type %>
</p>

<p>
  <strong>Press url:</strong>
  <%= @exhibition.press_url %>
</p>

<p>
  <strong>Curator:</strong>
  <%= @exhibition.curator %>
</p>

<p>
  <strong>Start month:</strong>
  <%= @exhibition.start_month %>
</p>

<p>
  <strong>Finish month:</strong>
  <%= @exhibition.finish_month %>
</p>

<p>
  <strong>Year:</strong>
  <%= @exhibition.year %>
</p>

<p>
  <strong>Exhibition image url:</strong>
  <%= @exhibition.exhibition_image_url %>
</p>

<p>
  <strong>Exhibition image url2:</strong>
  <%= @exhibition.exhibition_image_url2 %>
</p>

<%= link_to 'Edit', edit_admin_exhibition_path(@exhibition) %> |
<%= link_to 'Back', admin_exhibitions_path %>