config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'
  resources :exhibitions
  resources :venues
  resources :artworks

  get 'sessions/new' => 'sessions#new'
  
  post 'sessions' => 'sessions#create'
  
  delete 'sessions' => 'sessions#destroy'

  namespace :admin, defaults: {format: :html} do
    root to: '/sessions#new'
    resources :exhibitions
    resources :venues
    resources :artworks
    resources :artwork_images
  end

end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  has_many :artwork_images
  belongs_to :exhibition

  
end

app/controllers/admin/artworks_controller.rb
module Admin 
  class ArtworksController < ApplicationController
    before_action :set_artwork, only: [:show, :edit, :update, :destroy]
  
    # GET /artworks
    # GET /artworks.json
    def index
      @artworks = Artwork.all
    end
  
    # GET /artworks/1
    # GET /artworks/1.json
    def show
    end
  
    # GET /artworks/new
    def new
      @artwork = Artwork.new
    end
  
    # GET /artworks/1/edit
    def edit
    end
  
    # POST /artworks
    # POST /artworks.json
    def create
      @artwork = Artwork.new(artwork_params)
  
      respond_to do |format|
        if @artwork.save
          format.html { redirect_to admin_artworks_path, notice: 'Artwork was successfully created.' }
          format.json { render :show, status: :created, location: @artwork }
        else
          format.html { render :new }
          format.json { render json: @artwork.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /artworks/1
    # PATCH/PUT /artworks/1.json
    def update
      respond_to do |format|
        if @artwork.update(artwork_params)
          format.html { redirect_to admin_artworks_path, notice: 'Artwork was successfully updated.' }
          format.json { render :show, status: :ok, location: @artwork }
        else
          format.html { render :edit }
          format.json { render json: @artwork.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /artworks/1
    # DELETE /artworks/1.json
    def destroy
      @artwork.destroy
      respond_to do |format|
        format.html { redirect_to artworks_url, notice: 'Artwork was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_artwork
        @artwork = Artwork.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def artwork_params
        params.require(:artwork).permit(:title, :year_started, :year_completed, :exhibition_id, :mediums, :height, :width, :depth)
      end
  end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artwork, only: [:show, :edit, :update, :destroy]

  # GET /artworks
  # GET /artworks.json
  def index
    @artworks = Artwork.all
  end

  # GET /artworks/1
  # GET /artworks/1.json
  def show
  end

  # GET /artworks/new
  def new
    @artwork = Artwork.new
  end

  # GET /artworks/1/edit
  def edit
  end

  # POST /artworks
  # POST /artworks.json
  def create
    @artwork = Artwork.new(artwork_params)

    respond_to do |format|
      if @artwork.save
        format.html { redirect_to @artwork, notice: 'Artwork was successfully created.' }
        format.json { render :show, status: :created, location: @artwork }
      else
        format.html { render :new }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artworks/1
  # PATCH/PUT /artworks/1.json
  def update
    respond_to do |format|
      if @artwork.update(artwork_params)
        format.html { redirect_to @artwork, notice: 'Artwork was successfully updated.' }
        format.json { render :show, status: :ok, location: @artwork }
      else
        format.html { render :edit }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1
  # DELETE /artworks/1.json
  def destroy
    @artwork.destroy
    respond_to do |format|
      format.html { redirect_to artworks_url, notice: 'Artwork was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artwork
      @artwork = Artwork.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artwork_params
      params.require(:artwork).permit(:title, :year_started, :year_completed, :exhibition_id, :mediums, :height, :width, :depth)
    end
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/views/admin/artworks/_form.html.erb
<%= link_to 'ADD AN IMAGE FOR THIS ARTWORK', new_admin_artwork_image_path(artwork_id: @artwork.id) %>

<%= form_for(@artwork, url: admin_artwork_path) do |f| %>
  <% if @artwork.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artwork.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
      <% @artwork.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :year_started %><br>
    <%= f.number_field :year_started %>
  </div>
  <div class="field">
    <%= f.label :year_completed %><br>
    <%= f.number_field :year_completed %>
  </div>
  <div class="field">
    <%= collection_select(:artwork, :exhibition_id, Exhibition.all, :id, :title) %>
  </div>
  <div class="field">
    <%= f.label 'media' %><br>
    <%= f.text_field :mediums %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :width %><br>
    <%= f.number_field :width %>
  </div>
  <div class="field">
    <%= f.label :depth %><br>
    <%= f.number_field :depth %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/admin/artworks/edit.html.erb
<h1>Editing Artwork</h1>

<%= render 'form' %>

<%= link_to 'Show', @artwork %> |
<%= link_to 'Back', admin_artworks_path %>

app/views/admin/artworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Work</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Year started</th>
      <th>Images</th>
      <th>Exhibition</th>
      <th>Media</th>
      <th>Height</th>
      <th>Width</th>
      <th>Depth</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artworks.each do |artwork| %>
      <tr>
        <td><%= truncate(artwork.title) %></td>
        <td><%= artwork.year_started %></td>
        <td><%= artwork.artwork_images_count || 0 %></td>
        <td><%= truncate(Exhibition.find(artwork.exhibition_id).title) if artwork.exhibition_id %></td>
        <td><%= truncate(artwork.mediums) %></td>
        <td><%= artwork.height %></td>
        <td><%= artwork.width %></td>
        <td><%= artwork.depth %></td>
        <td><%= link_to 'Details', admin_artwork_path(artwork) %></td>
        <td><%= link_to 'Edit', edit_admin_artwork_path(artwork) %></td>
        <td><%= link_to 'Delete', artwork, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artwork', new_admin_artwork_path %>

app/views/admin/artworks/new.html.erb
<h1>New Artwork</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_artworks_path %>

app/views/admin/artworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @artwork.title %>
</p>

<p>
  <strong>Year started:</strong>
  <%= @artwork.year_started %>
</p>

<p>
  <strong>Year completed:</strong>
  <%= @artwork.year_completed %>
</p>

<p>
  <strong>Exhibition:</strong>
  <%= @artwork.exhibition_id %>
</p>

<p>
  <strong>Media:</strong>
  <%= @artwork.mediums %>
</p>

<p>
  <strong>Dimensions:</strong>
  <%= @artwork.height %>" H x <%= @artwork.width %>" W x <%= @artwork.depth %>" D
</p>



<%= link_to 'Edit', edit_admin_artwork_path(@artwork) %> |
<%= link_to 'Back', admin_artworks_path %>