config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#index'
  resources :exhibitions
  resources :venues
  resources :artworks

  get 'sessions/new' => 'sessions#new'
  
  post 'sessions' => 'sessions#create'
  
  delete 'sessions' => 'sessions#destroy'

  namespace :admin, defaults: {format: :html} do
    root to: '/sessions#new'
    resources :exhibitions
    resources :venues
    resources :artworks
    resources :artwork_images
  end

end

app/models/artwork_image.rb
class ArtworkImage < ActiveRecord::Base
  belongs_to :artwork, counter_cache: true
end

app/controllers/admin/artwork_images_controller.rb
 module Admin 
  class ArtworkImagesController < ApplicationController
    before_action :set_artwork_image, only: [:show, :edit, :update, :destroy]
  
    # GET /artwork_images
    # GET /artwork_images.json
    def index
      @artwork_images = ArtworkImage.all
    end
  
    # GET /artwork_images/1
    # GET /artwork_images/1.json
    def show
    end
  
    # GET /artwork_images/new
    def new
      @artwork_image = ArtworkImage.new(artwork_id: params[:artwork_id])
    end
  
    # GET /artwork_images/1/edit
    def edit
    end
  
    # POST /artwork_images
    # POST /artwork_images.json
    def create()
      @artwork_image = ArtworkImage.new(artwork_image_params)
  
      respond_to do |format|
        if @artwork_image.save
          format.html { redirect_to admin_artwork_images_path, notice: 'Artwork was successfully created.' }
          format.json { render :show, status: :created, location: @artwork }
        else
          format.html { render :new }
          format.json { render json: @artwork.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /artwork_images/1
    # PATCH/PUT /artwork_images/1.json
    def update
      respond_to do |format|
        if @artwork_image.update(artwork_image_params)
          format.html { redirect_to @artwork_image, notice: 'Artwork Image was successfully updated.' }
          format.json { render :show, status: :ok, location: @artwork }
        else
          format.html { render :edit }
          format.json { render json: @artwork.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /artwork_images/1
    # DELETE /artwork_images/1.json
    def destroy
      @artwork_image.destroy
      respond_to do |format|
        format.html { redirect_to admin_artwork_images_url, notice: 'Artwork was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_artwork_image
        @artwork_image = ArtworkImage.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def artwork_image_params
        params.require(:artwork_image).permit(:description, :shot_type, :artwork_id, :image_url)
      end
  end
end

app/helpers/admin/artwork_images_helper.rb
module Admin::ArtworkImagesHelper
end

app/helpers/artwork_images_helper.rb
module ArtworkImagesHelper
end

app/views/admin/artwork_images/_form.html.erb
<%= form_for(@artwork_image, url: admin_artwork_images_path) do |f| %>
  <% if @artwork_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artwork_image.errors.count, "error") %> prohibited this artwork image from being saved:</h2>

      <ul>
      <% @artwork_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.hidden_field :artwork_id  %>
  <h2>ADD IMAGE FOR <%=Artwork.find(@artwork_image.artwork_id).title%></h2>
  <br>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :shot_type %><br>
    <%= f.text_field :shot_type %>
  </div>

  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/artwork_images/edit.html.erb
<h1>Editing Artwork Images</h1>

<%= render 'form' %>

<%= link_to 'Show', @artwork_image %> |
<%= link_to 'Back', admin_artwork_images_path %>

app/views/admin/artwork_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Artwork Images</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Description</th>
      <th>Shot Type</th>
      <th>Artwork </th>
      <th>Artwork ID </th>
      <th>Image URL</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artwork_images.each do |image| %>
      <tr>
        <td><%= image.id %></td>
        <td><%= image.description %></td>
        <td><%= image.shot_type %></td>
        <td><%= Artwork.find(image.artwork_id).title %></td>
        <td><%= image.artwork_id%></td>
        <td><%= link_to image.image_url, image.image_url if image.image_url %></td>
        <td><%= link_to 'Show', admin_artwork_image_path(image) %></td>
        <td><%= link_to 'Edit', edit_admin_artwork_image_path(image) %></td>
        <td><%= link_to 'Destroy', admin_artwork_image_path(image), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back to artworks', admin_artworks_path %>

app/views/admin/artwork_images/new.html.erb
<h1>New Artwork Image</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_artwork_images_path %>

app/views/admin/artwork_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artwork ID:</strong>
  <%= @artwork_image.artwork_id %>
</p>

<p>
  <strong>Image URL:</strong>
  <%= @artwork_image.image_url %>
</p>

<img src="<%=@artwork_image.image_url%>">


<%= link_to 'Edit', edit_admin_artwork_image_path(@artwork_image) %> |
<%= link_to 'Back', admin_artwork_images_path %>